flowchart TD
  A[登入系統] --> B[進入 I/O 單管理]
  B --> C[新增 I/O 單]
  C --> D[填寫 I/O 表單資訊]
  D --> E[儲存後顯示提示框：繼續新增廣告活動？]
  E -->|是| F[新增廣告活動]
  F --> G[填寫活動資訊]
  G --> H[儲存後顯示提示框：繼續新增廣告組合？]
  H -->|是| I[新增廣告組合]
  I --> J[選擇格式與指定素材包]
  J --> K{Studio 格式素材包是否已建立？}
  K -->|是| L[選擇素材包 → 填完欄位 → 儲存完成]
  K -->|否| M[素材包下拉無資料]
  M -.-> N[點擊新增素材包]
  N --> O[顯示 Message box 轉址確認]
  O --> |是| P[新開視窗] -- redirect Studio --> Q{該格式對應單一 Studio 格式?}
  Q --> |是| R[進入到 Studio 該格式建立畫面]
  Q --> |否| S[進入到 Studio 建立格式選擇畫面（僅顯示該格式對應之多格式）]
  S --> T[建立完成] --> L

  class N warning;